# Generated by Django 5.2.4 on 2025-07-20 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokelib', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evolutionchain',
            name='pokemon',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='evolution_chain', to='pokelib.pokemons'),
            preserve_default=False,
        ),
    ]
