# Generated by Django 5.2.4 on 2025-07-20 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokelib', '0002_evolutionchain_pokemon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evolutionchain',
            old_name='pok_species',
            new_name='species',
        ),
    ]
