# Generated by Django 5.2.4 on 2025-07-21 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokelib', '0003_rename_pok_species_evolutionchain_species'),
    ]

    operations = [
        migrations.AddField(
            model_name='evolutionchain',
            name='pok_species',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
